export const AppErrorCode = {
  // ─── Auth ───
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
  AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_PHONE_ALREADY_REGISTERED: 'AUTH_PHONE_ALREADY_REGISTERED',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',
  AUTH_RESET_TOKEN_USED: 'AUTH_RESET_TOKEN_USED',
  AUTH_RESET_TOKEN_EXPIRED: 'AUTH_RESET_TOKEN_EXPIRED',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_ATTEMPTS_EXCEEDED: 'AUTH_OTP_ATTEMPTS_EXCEEDED',
  AUTH_VERIFICATION_TOKEN_INVALID: 'AUTH_VERIFICATION_TOKEN_INVALID',
  AUTH_VERIFICATION_TOKEN_TYPE_INVALID: 'AUTH_VERIFICATION_TOKEN_TYPE_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_SUSPENDED: 'AUTH_ACCOUNT_SUSPENDED',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',

  // ─── Authorization ───
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_VENDOR_ONLY: 'AUTH_VENDOR_ONLY',
  AUTH_ADMIN_ONLY: 'AUTH_ADMIN_ONLY',
  AUTH_CUSTOMER_ONLY: 'AUTH_CUSTOMER_ONLY',
  AUTH_STORE_OWNER_ONLY: 'AUTH_STORE_OWNER_ONLY',
  AUTH_PRODUCT_OWNER_ONLY: 'AUTH_PRODUCT_OWNER_ONLY',
  AUTH_ORDER_OWNER_ONLY: 'AUTH_ORDER_OWNER_ONLY',

  // ─── User ───
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_ALREADY_EXISTS: 'USER_EMAIL_ALREADY_EXISTS',
  USER_PHONE_ALREADY_EXISTS: 'USER_PHONE_ALREADY_EXISTS',
  USER_PASSWORDS_DO_NOT_MATCH: 'USER_PASSWORDS_DO_NOT_MATCH',
  USER_CURRENT_PASSWORD_INCORRECT: 'USER_CURRENT_PASSWORD_INCORRECT',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  USER_ALREADY_HAS_STORE: 'USER_ALREADY_HAS_STORE',

  // ─── Store ───
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_SLUG_NOT_FOUND: 'STORE_SLUG_NOT_FOUND',
  STORE_VENDOR_NOT_FOUND: 'STORE_VENDOR_NOT_FOUND',
  STORE_EMAIL_NOT_FOUND: 'STORE_EMAIL_NOT_FOUND',
  STORE_VENDOR_EMAIL_REQUIRED: 'STORE_VENDOR_EMAIL_REQUIRED',
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  STORE_NOT_ACTIVE: 'STORE_NOT_ACTIVE',
  STORE_NOT_VERIFIED: 'STORE_NOT_VERIFIED',
  STORE_CATEGORY_LIMIT_EXCEEDED: 'STORE_CATEGORY_LIMIT_EXCEEDED',
  STORE_HAS_PRODUCTS: 'STORE_HAS_PRODUCTS',
  STORE_CANNOT_PUBLISH_EMPTY: 'STORE_CANNOT_PUBLISH_EMPTY',

  // ─── Product ───
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_ACCESS_DENIED: 'PRODUCT_ACCESS_DENIED',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  PRODUCT_HIDDEN: 'PRODUCT_HIDDEN',
  PRODUCT_NOT_APPROVED: 'PRODUCT_NOT_APPROVED',
  PRODUCT_VARIANT_REQUIRED: 'PRODUCT_VARIANT_REQUIRED',
  PRODUCT_ALREADY_EXISTS: 'PRODUCT_ALREADY_EXISTS',
  PRODUCT_CANNOT_DELETE_HAS_ORDERS: 'PRODUCT_CANNOT_DELETE_HAS_ORDERS',
  PRODUCT_PRICE_INVALID: 'PRODUCT_PRICE_INVALID',
  PRODUCT_IMAGE_REQUIRED: 'PRODUCT_IMAGE_REQUIRED',
  PRODUCT_NAME_REQUIRED: 'PRODUCT_NAME_REQUIRED',

  // ─── Category ───
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_ALREADY_EXISTS: 'CATEGORY_ALREADY_EXISTS',
  CATEGORY_SLUG_DUPLICATE: 'CATEGORY_SLUG_DUPLICATE',
  SUBCATEGORY_NOT_FOUND: 'SUBCATEGORY_NOT_FOUND',
  SUBCATEGORY_HAS_PRODUCTS: 'SUBCATEGORY_HAS_PRODUCTS',
  SUBCATEGORY_ALREADY_EXISTS: 'SUBCATEGORY_ALREADY_EXISTS',

  // ─── Order ───
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  ORDER_CANNOT_TRANSITION: 'ORDER_CANNOT_TRANSITION',
  ORDER_WILAYA_COMMUNE_REQUIRED: 'ORDER_WILAYA_COMMUNE_REQUIRED',
  ORDER_PRODUCT_NOT_AVAILABLE: 'ORDER_PRODUCT_NOT_AVAILABLE',
  ORDER_TOTAL_MISMATCH: 'ORDER_TOTAL_MISMATCH',
  ORDER_DELIVERY_CREATION_FAILED: 'ORDER_DELIVERY_CREATION_FAILED',
  ORDER_ONLY_CONFIRMED_CAN_SHIP: 'ORDER_ONLY_CONFIRMED_CAN_SHIP',
  ORDER_ALREADY_CANCELLED: 'ORDER_ALREADY_CANCELLED',
  ORDER_ALREADY_DELIVERED: 'ORDER_ALREADY_DELIVERED',
  ORDER_ALREADY_REFUNDED: 'ORDER_ALREADY_REFUNDED',
  ORDER_CANNOT_CANCEL_AFTER_SHIPPED: 'ORDER_CANNOT_CANCEL_AFTER_SHIPPED',
  ORDER_CANNOT_PURCHASE_OWN_PRODUCT: 'ORDER_CANNOT_PURCHASE_OWN_PRODUCT',
  ORDER_CANNOT_REVIEW_TWICE: 'ORDER_CANNOT_REVIEW_TWICE',
  ORDER_MINIMUM_NOT_REACHED: 'ORDER_MINIMUM_NOT_REACHED',
  ORDER_CUSTOMER_INFO_INCOMPLETE: 'ORDER_CUSTOMER_INFO_INCOMPLETE',
  ORDER_AT_LEAST_ONE_ITEM: 'ORDER_AT_LEAST_ONE_ITEM',
  ORDER_INVALID_ITEM: 'ORDER_INVALID_ITEM',
  ORDER_STOPDESK_CODE_REQUIRED: 'ORDER_STOPDESK_CODE_REQUIRED',
  ORDER_REFUND_NOT_ALLOWED: 'ORDER_REFUND_NOT_ALLOWED',

  // ─── Delivery ───
  DELIVERY_COMPANY_NOT_ASSIGNED: 'DELIVERY_COMPANY_NOT_ASSIGNED',
  DELIVERY_HANDLER_NOT_FOUND: 'DELIVERY_HANDLER_NOT_FOUND',
  DELIVERY_CREDENTIALS_NOT_CONFIGURED: 'DELIVERY_CREDENTIALS_NOT_CONFIGURED',
  DELIVERY_API_ERROR: 'DELIVERY_API_ERROR',
  DELIVERY_API_TIMEOUT: 'DELIVERY_API_TIMEOUT',
  DELIVERY_API_RATE_LIMITED: 'DELIVERY_API_RATE_LIMITED',
  DELIVERY_INVALID_WILAYA: 'DELIVERY_INVALID_WILAYA',
  DELIVERY_TERRITORY_NOT_SYNCED: 'DELIVERY_TERRITORY_NOT_SYNCED',
  DELIVERY_MAX_BATCH_EXCEEDED: 'DELIVERY_MAX_BATCH_EXCEEDED',
  DELIVERY_ORDER_NOT_IN_RESPONSE: 'DELIVERY_ORDER_NOT_IN_RESPONSE',
  DELIVERY_UNKNOWN_ERROR: 'DELIVERY_UNKNOWN_ERROR',

  // ─── Delivery Fees ───
  FEE_NOT_FOUND_FOR_WILAYA: 'FEE_NOT_FOUND_FOR_WILAYA',
  FEE_API_CREDENTIALS_MISSING: 'FEE_API_CREDENTIALS_MISSING',
  FEE_API_ERROR: 'FEE_API_ERROR',
  FEE_API_NO_DATA: 'FEE_API_NO_DATA',
  FEE_FETCH_FAILED: 'FEE_FETCH_FAILED',

  // ─── Upload ───
  UPLOAD_NO_FILE_PROVIDED: 'UPLOAD_NO_FILE_PROVIDED',
  UPLOAD_MAX_FILES_EXCEEDED: 'UPLOAD_MAX_FILES_EXCEEDED',
  UPLOAD_NO_KEY_PROVIDED: 'UPLOAD_NO_KEY_PROVIDED',
  UPLOAD_INVALID_FILE_TYPE: 'UPLOAD_INVALID_FILE_TYPE',
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_R2_ACCESS_DENIED: 'UPLOAD_R2_ACCESS_DENIED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  UPLOAD_DELETE_FAILED: 'UPLOAD_DELETE_FAILED',

  // ─── Tracking ───
  TRACKING_CONFIG_NOT_FOUND: 'TRACKING_CONFIG_NOT_FOUND',
  TRACKING_META_API_FAILED: 'TRACKING_META_API_FAILED',
  TRACKING_TIKTOK_API_FAILED: 'TRACKING_TIKTOK_API_FAILED',

  // ─── Audit ───
  AUDIT_ACTION_NOT_FOUND: 'AUDIT_ACTION_NOT_FOUND',
  AUDIT_UNAUTHORIZED: 'AUDIT_UNAUTHORIZED',

  // ─── Infrastructure ───
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT: 'EXTERNAL_API_TIMEOUT',

  // ─── Validation ───
  VALIDATION_MUST_BE_STRING: 'VALIDATION_MUST_BE_STRING',
  VALIDATION_INVALID_EMAIL: 'VALIDATION_INVALID_EMAIL',
  VALIDATION_REQUIRED: 'VALIDATION_REQUIRED',
  VALIDATION_MIN_LENGTH: 'VALIDATION_MIN_LENGTH',
  VALIDATION_MIN_VALUE: 'VALIDATION_MIN_VALUE',
  VALIDATION_INVALID_VALUE: 'VALIDATION_INVALID_VALUE',
  VALIDATION_INVALID_ID: 'VALIDATION_INVALID_ID',
  VALIDATION_ARRAY_MIN_SIZE: 'VALIDATION_ARRAY_MIN_SIZE',
  VALIDATION_ARRAY_MAX_SIZE: 'VALIDATION_ARRAY_MAX_SIZE',
  VALIDATION_AT_LEAST_ONE_LANGUAGE: 'VALIDATION_AT_LEAST_ONE_LANGUAGE',
  VALIDATION_AT_LEAST_ONE_IMAGE: 'VALIDATION_AT_LEAST_ONE_IMAGE',

  // ─── Coupon ───
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_EXHAUSTED: 'COUPON_EXHAUSTED',
  COUPON_MINIMUM_NOT_REACHED: 'COUPON_MINIMUM_NOT_REACHED',
  COUPON_INVALID: 'COUPON_INVALID',

  // ─── Payment ───
  PAYMENT_ALREADY_COMPLETED: 'PAYMENT_ALREADY_COMPLETED',
} as const;

export type AppErrorCodeType = (typeof AppErrorCode)[keyof typeof AppErrorCode];
