import { HttpStatus } from '@nestjs/common';
import { AppErrorCode } from './error-codes.enum';

export const ERROR_HTTP_STATUS: Record<string, number> = {
  // ─── Auth (401, 403, 404, 409) ───
  [AppErrorCode.AUTH_INVALID_CREDENTIALS]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_INVALID_REFRESH_TOKEN]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_REFRESH_TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_EMAIL_ALREADY_REGISTERED]: HttpStatus.CONFLICT,
  [AppErrorCode.AUTH_PHONE_ALREADY_REGISTERED]: HttpStatus.CONFLICT,
  [AppErrorCode.AUTH_RESET_TOKEN_INVALID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_RESET_TOKEN_USED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_RESET_TOKEN_EXPIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_OTP_INVALID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_OTP_EXPIRED]: HttpStatus.GONE,
  [AppErrorCode.AUTH_OTP_ATTEMPTS_EXCEEDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_VERIFICATION_TOKEN_INVALID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_VERIFICATION_TOKEN_TYPE_INVALID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.AUTH_TOKEN_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_TOKEN_INVALID]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_TOKEN_REVOKED]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_SESSION_EXPIRED]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.AUTH_ACCOUNT_DISABLED]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_ACCOUNT_LOCKED]: HttpStatus.LOCKED,
  [AppErrorCode.AUTH_ACCOUNT_SUSPENDED]: HttpStatus.FORBIDDEN,

  // ─── Authorization ───
  [AppErrorCode.AUTH_UNAUTHORIZED]: HttpStatus.UNAUTHORIZED,
  [AppErrorCode.AUTH_INSUFFICIENT_PERMISSIONS]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_VENDOR_ONLY]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_ADMIN_ONLY]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_CUSTOMER_ONLY]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_STORE_OWNER_ONLY]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_PRODUCT_OWNER_ONLY]: HttpStatus.FORBIDDEN,
  [AppErrorCode.AUTH_ORDER_OWNER_ONLY]: HttpStatus.FORBIDDEN,

  // ─── User ───
  [AppErrorCode.USER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.USER_EMAIL_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [AppErrorCode.USER_PHONE_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [AppErrorCode.USER_PASSWORDS_DO_NOT_MATCH]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.USER_CURRENT_PASSWORD_INCORRECT]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.USER_PROFILE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.USER_ALREADY_HAS_STORE]: HttpStatus.CONFLICT,

  // ─── Store ───
  [AppErrorCode.STORE_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.STORE_SLUG_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.STORE_VENDOR_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.STORE_EMAIL_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.STORE_VENDOR_EMAIL_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.STORE_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [AppErrorCode.STORE_NOT_ACTIVE]: HttpStatus.FORBIDDEN,
  [AppErrorCode.STORE_CATEGORY_LIMIT_EXCEEDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.STORE_HAS_PRODUCTS]: HttpStatus.CONFLICT,
  [AppErrorCode.STORE_CANNOT_PUBLISH_EMPTY]: HttpStatus.BAD_REQUEST,

  // ─── Product ───
  [AppErrorCode.PRODUCT_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.PRODUCT_ACCESS_DENIED]: HttpStatus.FORBIDDEN,
  [AppErrorCode.PRODUCT_OUT_OF_STOCK]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.PRODUCT_ARCHIVED]: HttpStatus.GONE,
  [AppErrorCode.PRODUCT_HIDDEN]: HttpStatus.NOT_FOUND,
  [AppErrorCode.PRODUCT_NOT_APPROVED]: HttpStatus.FORBIDDEN,
  [AppErrorCode.PRODUCT_VARIANT_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.PRODUCT_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [AppErrorCode.PRODUCT_CANNOT_DELETE_HAS_ORDERS]: HttpStatus.CONFLICT,
  [AppErrorCode.PRODUCT_PRICE_INVALID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.PRODUCT_IMAGE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.PRODUCT_NAME_REQUIRED]: HttpStatus.BAD_REQUEST,

  // ─── Category ───
  [AppErrorCode.CATEGORY_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.CATEGORY_HAS_PRODUCTS]: HttpStatus.CONFLICT,
  [AppErrorCode.CATEGORY_ALREADY_EXISTS]: HttpStatus.CONFLICT,
  [AppErrorCode.CATEGORY_SLUG_DUPLICATE]: HttpStatus.CONFLICT,
  [AppErrorCode.SUBCATEGORY_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.SUBCATEGORY_HAS_PRODUCTS]: HttpStatus.CONFLICT,
  [AppErrorCode.SUBCATEGORY_ALREADY_EXISTS]: HttpStatus.CONFLICT,

  // ─── Order ───
  [AppErrorCode.ORDER_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.ORDER_INVALID_STATUS]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_CANNOT_TRANSITION]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_WILAYA_COMMUNE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_PRODUCT_NOT_AVAILABLE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_TOTAL_MISMATCH]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_DELIVERY_CREATION_FAILED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_ONLY_CONFIRMED_CAN_SHIP]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_ALREADY_CANCELLED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_ALREADY_DELIVERED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_ALREADY_REFUNDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_CANNOT_CANCEL_AFTER_SHIPPED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_CANNOT_PURCHASE_OWN_PRODUCT]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_CANNOT_REVIEW_TWICE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_MINIMUM_NOT_REACHED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_CUSTOMER_INFO_INCOMPLETE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_AT_LEAST_ONE_ITEM]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_INVALID_ITEM]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_STOPDESK_CODE_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.ORDER_REFUND_NOT_ALLOWED]: HttpStatus.BAD_REQUEST,

  // ─── Delivery ───
  [AppErrorCode.DELIVERY_COMPANY_NOT_ASSIGNED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_HANDLER_NOT_FOUND]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_CREDENTIALS_NOT_CONFIGURED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_API_ERROR]: HttpStatus.BAD_GATEWAY,
  [AppErrorCode.DELIVERY_API_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,
  [AppErrorCode.DELIVERY_API_RATE_LIMITED]: HttpStatus.TOO_MANY_REQUESTS,
  [AppErrorCode.DELIVERY_INVALID_WILAYA]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_TERRITORY_NOT_SYNCED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_MAX_BATCH_EXCEEDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.DELIVERY_ORDER_NOT_IN_RESPONSE]: HttpStatus.INTERNAL_SERVER_ERROR,
  [AppErrorCode.DELIVERY_UNKNOWN_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,

  // ─── Delivery Fees ───
  [AppErrorCode.FEE_NOT_FOUND_FOR_WILAYA]: HttpStatus.NOT_FOUND,
  [AppErrorCode.FEE_API_CREDENTIALS_MISSING]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.FEE_API_ERROR]: HttpStatus.BAD_GATEWAY,
  [AppErrorCode.FEE_API_NO_DATA]: HttpStatus.BAD_GATEWAY,
  [AppErrorCode.FEE_FETCH_FAILED]: HttpStatus.BAD_GATEWAY,

  // ─── Upload ───
  [AppErrorCode.UPLOAD_NO_FILE_PROVIDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.UPLOAD_MAX_FILES_EXCEEDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.UPLOAD_NO_KEY_PROVIDED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.UPLOAD_INVALID_FILE_TYPE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.UPLOAD_FILE_TOO_LARGE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.UPLOAD_R2_ACCESS_DENIED]: HttpStatus.INTERNAL_SERVER_ERROR,
  [AppErrorCode.UPLOAD_FAILED]: HttpStatus.INTERNAL_SERVER_ERROR,
  [AppErrorCode.UPLOAD_DELETE_FAILED]: HttpStatus.INTERNAL_SERVER_ERROR,

  // ─── Tracking ───
  [AppErrorCode.TRACKING_CONFIG_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.TRACKING_META_API_FAILED]: HttpStatus.BAD_GATEWAY,
  [AppErrorCode.TRACKING_TIKTOK_API_FAILED]: HttpStatus.BAD_GATEWAY,

  // ─── Audit ───
  [AppErrorCode.AUDIT_ACTION_NOT_FOUND]: HttpStatus.NOT_FOUND,
  [AppErrorCode.AUDIT_UNAUTHORIZED]: HttpStatus.FORBIDDEN,

  // ─── Infrastructure ───
  [AppErrorCode.INTERNAL_SERVER_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [AppErrorCode.VALIDATION_FAILED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.INVALID_ID_FORMAT]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.REQUEST_TIMEOUT]: HttpStatus.REQUEST_TIMEOUT,
  [AppErrorCode.RATE_LIMIT_EXCEEDED]: HttpStatus.TOO_MANY_REQUESTS,
  [AppErrorCode.DATABASE_ERROR]: HttpStatus.INTERNAL_SERVER_ERROR,
  [AppErrorCode.SERVICE_UNAVAILABLE]: HttpStatus.SERVICE_UNAVAILABLE,
  [AppErrorCode.EXTERNAL_API_ERROR]: HttpStatus.BAD_GATEWAY,
  [AppErrorCode.EXTERNAL_API_TIMEOUT]: HttpStatus.GATEWAY_TIMEOUT,

  // ─── Validation ───
  [AppErrorCode.VALIDATION_MUST_BE_STRING]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_INVALID_EMAIL]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_REQUIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_MIN_LENGTH]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_MIN_VALUE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_INVALID_VALUE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_INVALID_ID]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_ARRAY_MIN_SIZE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_ARRAY_MAX_SIZE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_AT_LEAST_ONE_LANGUAGE]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.VALIDATION_AT_LEAST_ONE_IMAGE]: HttpStatus.BAD_REQUEST,

  // ─── Coupon ───
  [AppErrorCode.COUPON_EXPIRED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.COUPON_EXHAUSTED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.COUPON_MINIMUM_NOT_REACHED]: HttpStatus.BAD_REQUEST,
  [AppErrorCode.COUPON_INVALID]: HttpStatus.BAD_REQUEST,

  // ─── Payment ───
  [AppErrorCode.PAYMENT_ALREADY_COMPLETED]: HttpStatus.BAD_REQUEST,
};
