export enum AuditAction {
  USER_REGISTER = 'USER_REGISTER',
  VENDOR_APPLY = 'VENDOR_APPLY',
  VENDOR_APPROVE = 'VENDOR_APPROVE',
  VENDOR_REJECT = 'VENDOR_REJECT',
  PRODUCT_CREATE = 'PRODUCT_CREATE',
  PRODUCT_UPDATE = 'PRODUCT_UPDATE',
  PRODUCT_DELETE = 'PRODUCT_DELETE',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_STATUS_CHANGE = 'ORDER_STATUS_CHANGE',
  STORE_CREATE = 'STORE_CREATE',
  STORE_UPDATE = 'STORE_UPDATE'
}
